# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6883180dab346020f625937880a6d7e5a3e5bf515b9a898a32f7446e1444fdf61aa96805aad3a36e5b3a5c099e76639a35e5b69a6c8b82f46c051e8210d641be

test:
  secret_key_base: 41740195dcb99ce05eda30f4eb63fb580d75406b07f3f01cd83be939dcccf80c3cebfcaca13dce4188519df19dba946d99f8546d07a698b2297cb678a14018e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
